version: '3.7'

networks:
    shopware:

services:
  app_server:
    image: shopware/development:7.4-composer-2
    networks:
      shopware:
        aliases:
          - docker.vm
    extra_hosts:
      - "docker.vm:127.0.0.1"
      - "host.docker.internal:host-gateway"
    volumes:
      - ~/.composer:/.composer
    tmpfs:
      - /tmp:mode=1777
    environment:
      - "TZ=Europe/Vienna"
      - "XDEBUG_ENABLED=1"

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      shopware:
        aliases:
          - mysql

  cypress:
    image: cypress/included:5.6.0
    tty: true
    ipc: host
    environment:
      - CYPRESS_baseUrl=http://docker.vm:8000
      - DISPLAY
    networks:
      shopware:
    volumes:
      - ./tests/e2e:/e2e
      # for Cypress to communicate with the X11 server pass this socket file
      # in addition to any other mapped volumes
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /bin/bash

  mailhog:
    image: mailhog/mailhog
    networks:
      shopware:
        aliases:
          - mailhog

  adminer:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
        PMA_USER: app
        PMA_PASSWORD: app
        PMA_HOST: app_mysql
    stdin_open: true
    volumes:
        - /session
    tty: true
    ports:
        - 9595:80/tcp
    networks:
        shopware:
            aliases:
                - mysql


  elasticsearch:
    image: elastic/elasticsearch:7.8.0
    networks:
        shopware:
            aliases:
                - elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
